version: "3.8"

services:
  app:
    build: .
    container_name: taskms-app
    restart: always
    ports:
      - "8080:80"
    environment:
      DB_HOST: mysql
      DB_USER: taskms
      DB_PASS: taskms123
      DB_NAME: etms_db
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-taskms
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: etms_db
      MYSQL_USER: root
      MYSQL_PASSWORD: taskms123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-taskms
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"

volumes:
  mysql_data:
